/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './**/*.php',
    './**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim':        '#ffb5a0',
        'primary':                  '#ffb5a0',
        'surface':                  '#131313',
        'on-primary-container':     '#541200',
        'on-primary':               '#5f1500',
        'tertiary':                 '#f8b6b2',
        'background':               '#131313',
        'on-tertiary-container':    '#461e1d',
        'surface-container':        '#201f1f',
        'surface-container-lowest': '#0e0e0e',
        'on-surface':               '#e5e2e1',
        'on-surface-variant':       '#c9a99f',
        'inverse-primary':          '#b02f00',
        'outline':                  '#ab8980',
        'secondary-fixed-dim':      '#ffb3ac',
        'secondary-container':      '#a40213',
        'surface-tint':             '#ffb5a0',
        'surface-container-highest':'#353534',
        'primary-fixed':            '#ffdbd1',
        'on-primary-fixed-variant': '#862200',
        'secondary':                '#ffb3ac',
        'outline-variant':          '#5b4039',
        'on-background':            '#e5e2e1',
        'primary-container':        '#ff5722',
        'surface-variant':          '#353534',
        'surface-container-low':    '#1c1b1b',
        'surface-dim':              '#131313',
        'surface-container-high':   '#2a2a2a',
        'surface-bright':           '#393939',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      fontFamily: {
        'display-lg':        ['Literata'],
        'headline-xl':       ['Literata'],
        'label-caps':        ['Work Sans'],
        'headline-lg':       ['Literata'],
        'body-md':           ['Work Sans'],
        'body-lg':           ['Work Sans'],
        'display-lg-mobile': ['Literata'],
      },
      fontSize: {
        'display-lg':        ['62px', { lineHeight: '1.08', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl':       ['46px', { lineHeight: '1.2',  fontWeight: '700' }],
        'label-caps':        ['11px', { lineHeight: '1',    letterSpacing: '0.12em', fontWeight: '700' }],
        'headline-lg':       ['28px', { lineHeight: '1.3',  fontWeight: '700' }],
        'body-md':           ['15px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-lg':           ['17px', { lineHeight: '1.65', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.15', fontWeight: '800' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
